/*
 * Copyright 2020 ugurkara.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.sparrow.io.buffer.view;

import com.sparrow.io.buffer.BaseIOBuffer;
import com.sparrow.io.buffer.DataType;
import com.sparrow.io.buffer.IOBuffer;
import com.sparrow.io.buffer.IOBufferStatusListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ugurkara
 */
public class IOBufferView extends javax.swing.JPanel {

    /**
     * Creates new form IOBufferViewX
     */
    public IOBufferView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setRollover(true);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BOOLEAN", "BYTE", "SHORT", "USHORT", "INTEGER", "LONG", "FLOAT", "DOUBLE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Hex", "Binary" }));
        jToolBar1.add(jComboBox2);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private IOBuffer buffer = null;
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (buffer == null) {
            return;
        }

        int converterDataType = jComboBox2.getSelectedIndex();
        String selectedItem = (String) jComboBox1.getSelectedItem();
        DataType dataType = DataType.valueOf(selectedItem);
        BaseIOBuffer baseIOBuffer = buffer.ofBuffer(dataType);
        Converter converter = Converter.of(dataType, converterDataType);
        jTable1.setModel(new IOBufferTableModel(baseIOBuffer, converter));
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ((IOBufferTableModel) jTable1.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void update(IOBuffer buffer) {

        if (this.buffer != null) {
            this.buffer.removeStatusListener(statusListener);
        }
        buffer.addStatusListener(statusListener);
        int converterDataType = jComboBox2.getSelectedIndex();
        String selectedItem = (String) jComboBox1.getSelectedItem();
        DataType dataType = DataType.valueOf(selectedItem);
        BaseIOBuffer baseIOBuffer = buffer.ofBuffer(dataType);
        Converter converter = Converter.of(dataType, converterDataType);
        jTable1.setModel(new IOBufferTableModel(baseIOBuffer, converter));
        this.buffer = buffer;
    }

    private final IOBufferStatusListener statusListener = new IOBufferStatusListener() {
        @Override
        public void statusChanged(boolean bln) {
            jLabel1.setText(bln ? "ONLINE" : "OFFLINE");
            jLabel2.setText(new SimpleDateFormat("dd/MM/yyyy hh:mm:ss.ms").format(new Date(buffer.getTimeMillis())));
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
